version: "3.8"
name: "backend"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 7000:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: MONGO_123

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: MONGO_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: MONGO_123
      ME_CONFIG_MONGODB_URL: mongodb://MONGO_USER:MONGO_123@mongo:27017/

  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - 8090:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ["start-dev"]

  envoy:
    image: envoyproxy/envoy:dev-eb51ea0ff70a40cd4bbafc6f03333e38c62a2ca3
    ports:
      - "10000:10000"

  backend-cardlist:
    image: trello-v2/backend:1.1
    environment:
      - GRPC_HOST=0.0.0.0
      - PORT=3000
      - SERVICE_NAME=cardlist
      - DB_CONN_STR=mongodb://MONGO_USER:MONGO_123@mongo:27017/trello?authSource=admin
    ports:
      - 3010:3000
      - 3011:3001

  backend-board:
    image: trello-v2/backend:1.1
    environment:
      - GRPC_HOST=0.0.0.0
      - PORT=3000
      - SERVICE_NAME=board
      - DB_CONN_STR=mongodb://MONGO_USER:MONGO_123@mongo:27017/trello?authSource=admin
    ports:
      - 3020:3000
      - 3021:3001

  backend-workspace:
    image: trello-v2/backend:1.1
    environment:
      - GRPC_HOST=0.0.0.0
      - PORT=3000
      - SERVICE_NAME=workspace
      - DB_CONN_STR=mongodb://MONGO_USER:MONGO_123@mongo:27017/trello?authSource=admin
    ports:
      - 3030:3000
      - 3031:3001
